### ISSUE TITLE
listen EADDRINUSE Error

### ISSUE THREAD

**Issue by rikolumi** [nosco/opsync#1]
Hi,

I was trying to run the program and then I got EADDRINUSE error. I know this means the port is being used by other program. But, which port is opsync trying to use? I cant seems to figure it out..

Thanks.

Here is the console log:
rico@luminov-Dev1:~$ sudo opsync -f opsync/config.json 
{"uri":"http://127.0.0.1:4001","description":"client server","databases":{"meteor":{"priority":1,"collections":{"users":{"priority":10,"operations":["insert","update","delete"]}}}},"remotes":[{"uri":"http://192.168.1.118:27017","description":"central server","map":{"mydb0":"mydb"}}]}

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: listen EADDRINUSE
    at errnoException (net.js:905:11)
    at Server._listen2 (net.js:1043:14)
    at listen (net.js:1065:10)
    at Server.listen (net.js:1139:5)
    at Function.app.listen (/usr/local/lib/node_modules/opsync/node_modules/express/lib/application.js:546:24)
    at Opsync.run (/usr/local/lib/node_modules/opsync/lib/opsync.js:116:45)
    at Opsync.g (events.js:180:16)
    at Opsync.emit (events.js:92:17)
    at /usr/local/lib/node_modules/opsync/lib/opsync.js:89:10
    at /usr/local/lib/node_modules/opsync/node_modules/mongodb/lib/mongodb/mongo_client.js:472:11
rico@luminov-Dev1:~$ 5 Feb 17:04:39 - reading config file: /usr/local/lib/node_modules/opsync/bin/../lib/statsd/config.js
5 Feb 17:04:39 - server is up

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: listen EADDRINUSE
    at errnoException (net.js:905:11)
    at Server._listen2 (net.js:1043:14)
    at listen (net.js:1065:10)
    at Server.listen (net.js:1139:5)
    at /usr/local/lib/node_modules/opsync/node_modules/statsd/stats.js:359:16
    at null.<anonymous> (/usr/local/lib/node_modules/opsync/node_modules/statsd/lib/config.js:38:5)
    at emit (events.js:95:17)
    at /usr/local/lib/node_modules/opsync/node_modules/statsd/lib/config.js:20:12
    at fs.js:272:14
    at Object.oncomplete (fs.js:108:15)
^C

**Comment by eliasgs** [comment]
Hi there!

It will start a proxy server on the port specified in the configuration file (in your example port 4001). Other than that it would start a statsd server on port 8125 and 8126 - this has now been made optional (see 1b50525eb3a55328732937701118d3dba2645120).

Furthermore I don't know if it's intentional, but the remote you specified is set to mongodb's default port 27017?

Please let me know if updating to v0.16.0 solves your problem - or if you run into other issues:)

Thanks
Elias

**Comment by rikolumi** [comment]
Hi, thanks for the answer. Perhaps I'm not familiar with the whole setup process and how to configure it properly.

At first, I thought the first uri field in the config file was to specify the local database that opsync will listen to. That's why I get EADDRINUSE error.

So, this is my config file now after I updated to v0.16.0.
```
{
  "uri": "http://127.0.0.1:4001", //proxy port
  "description": "local db",
  "databases": {
    "meteor": {
      "priority": 1,
      "collections": {
        "users": {
          "priority": 10,
          "operations": ["insert", "update", "delete"]
        }
      }
    }
  },
  "remotes": [
    {
      "uri": "http://192.168.1.118:27017", // Remote database opsync will sync to?
      "description": "riko's computer",
      "map": {
        "meteor": "mydb"
      }
    }
  ]
}
```
Then I edit settings.js file. I assume this file is to specify my local database address that opsync will listen to.
```
exports.mongo = {
  uri: 'mongodb://127.0.0.1:2013/local',
  collection: 'opsync.rs'
};
```

And now I got this errors;
```
(node) warning: possible EventEmitter memory leak detected. 501 listeners added. Use emitter.setMaxListeners() to increase limit.
Trace
    at Queue.addListener (events.js:160:15)
    at Queue.once (events.js:185:8)
    at /usr/lib/node_modules/opsync/lib/queue.js:129:12
    at /usr/lib/node_modules/opsync/node_modules/mongodb/lib/mongodb/collection/query.js:164:5
    at /usr/lib/node_modules/opsync/node_modules/mongodb/lib/mongodb/cursor.js:758:35
    at Cursor.close (/usr/lib/node_modules/opsync/node_modules/mongodb/lib/mongodb/cursor.js:989:5)
    at Cursor.nextObject (/usr/lib/node_modules/opsync/node_modules/mongodb/lib/mongodb/cursor.js:758:17)
    at commandHandler (/usr/lib/node_modules/opsync/node_modules/mongodb/lib/mongodb/cursor.js:727:14)
    at /usr/lib/node_modules/opsync/node_modules/mongodb/lib/mongodb/db.js:1888:9
    at Server.Base._callHandler (/usr/lib/node_modules/opsync/node_modules/mongodb/lib/mongodb/connection/base.js:453:41)
```
Is there anything that I missed in the configuration steps?

**Comment by eliasgs** [comment]
Ok, I think I see the confusion. All communication between opsync instances go over http (this is due to some trouble we had with package loss when connecting via the mongodb driver over unstable internet connections).
This means that there must a running opsync instance on both of the machines. The http server opsync starts is on the port number specified in the configuration file.

So if I understand what you are trying to accomplish, you should have something like the following config on your first machine:
```
{
  "id": "server1",
  "uri": "http://127.0.0.1:4001",
  "description": "local db",
  "databases": {
    "meteor": {
      "priority": 1,
      "collections": {
        "users": { "priority": 10 }
      }
    }
  },
  "remotes": [
    {
      "id": "server2"
      "uri": "http://192.168.1.118:4001",
      "description": "riko's computer",
      "map": {
        "meteor": "mydb"
      }
    }
  ]
}
```

And something like the following on the other machine (assuming you want bidirectional synchronisation?)

```
{
  "id": "server2",
  "uri": "http://192.168.1.118:4001",
  "description": "riko's computer",
  "databases": {
    "mydb": {
      "priority": 1,
      "collections": {
        "users": { "priority": 10 }
      }
    }
  },
  "remotes": [
    {
      "id": "server1"
      "uri": "http://{server1}:4001",
      "description": "local db",
      "map": {
        "mydb": "meteor"
      }
    }
  ]
}
```

Also regarding settings.js: you are correct, the ``mongo.uri`` is the connection string to the database where opsync listens for changes (I made a small change in v0.16.1 so we no longer assume where the experimental statsd service should save data and also connect in a more consistent way).

Please let me know if you still get the above memory leak warning - I have not been able to replicate it. If it persists please send me the output of ``npm list``.

Thanks
Elias

**Comment by rikolumi** [comment]
Hi there,

It's working now, I decided to go with one direction sync because there was some problem with the bidirectional sync.

With these configuration I was able to sync from server2 to server1. It has good performance, and it could even queue the oplog when remote server is down and push the queue once remote server is up again. Here is my configuration file:
Server 1:
```
{
  "id": "server1",
  "uri": "http://127.0.0.1:2017",
  "description": "Server1 server",
  "databases": {
    "meteor": {
      "priority": 1,
      "collections": {
        "edc": {
          "priority": 10,
          "operations": ["insert","update","delete"]
        }
      }
    }
  }
}
```
Server 2:
```
{
  "id": "server2",
  "uri": "http://127.0.0.1:2015",
  "description": "riko computer",
  "databases": {
    "meteor": {
      "priority": 1,
      "collections": {
        "edc": {
          "priority": 10,
          "operations": ["insert", "update", "delete"]
        }
      }
    }
  },
  "remotes": [
    {
      "id": "server1",
      "uri": "http://192.168.1.108:2017",
      "description": "local db",
      "map": {
        "meteor": "meteor"
      }
    }
  ]
}
```
This error sometimes shows up, any idea what could have caused this?
```
________________________________________________________________________
=================================ERROR==================================
2015-02-12T02:48:49.629Z
------------------------------------------------------------------------
Could not process operation!
------------------------------------------------------------------------
<Opsync-Origin: server2>
{ date: '2015-02-12T02:48:49.629Z',
  origin: 'server2',
  body: '{"ts":"6114784899690921985","h":"-5933231280417799204","v":2,"op":"u","ns":"meteor.edc","o2":{"_id":"hraFquYhvC2vGBWj8"},"o":{"$set":{"lastEditedBy":"daniel","lastEditedDate":"2015-02-12T02:48:23.211Z","name":"Testin"}},"priority":"1#10#7.023905772703059e-13","uuid":"e9c6b0bc-3d64-44d3-b99d-8f3c210d91b2","map":{"meteor":"meteor"}}',
  err: 
   { [MongoError: E11000 duplicate key error index: local.opsync.ignore.$_id_  dup key: { : null }]
     name: 'MongoError',
     err: 'E11000 duplicate key error index: local.opsync.ignore.$_id_  dup key: { : null }',
     code: 11000,
     n: 0,
     lastOp: { _bsontype: 'Timestamp', low_: 4, high_: 1423709329 },
     connectionId: 294,
     ok: 1 },
  stack: 'Error\n    at /usr/lib/node_modules/opsync/lib/proxy.js:60:22\n    at /usr/lib/node_modules/opsync/lib/proxy.js:194:15\n    at /usr/lib/node_modules/opsync/node_modules/mongodb/lib/mongodb/collection/core.js:713:22\n    at /usr/lib/node_modules/opsync/node_modules/mongodb/lib/mongodb/collection/core.js:636:7\n    at Server.Base._callHandler (/usr/lib/node_modules/opsync/node_modules/mongodb/lib/mongodb/connection/base.js:453:41)\n    at /usr/lib/node_modules/opsync/node_modules/mongodb/lib/mongodb/connection/server.js:487:18\n    at MongoReply.parseBody (/usr/lib/node_modules/opsync/node_modules/mongodb/lib/mongodb/responses/mongo_reply.js:68:5)\n    at null.<anonymous> (/usr/lib/node_modules/opsync/node_modules/mongodb/lib/mongodb/connection/server.js:445:20)\n    at emit (events.js:95:17)\n    at null.<anonymous> (/usr/lib/node_modules/opsync/node_modules/mongodb/lib/mongodb/connection/connection_pool.js:201:13)' }
________________________________________________________________________
```

And also sometimes it shows this error.
```
Error: Trying to dequeue unpaused queue
    at Queue.dequeue (/usr/local/lib/node_modules/opsync/lib/queue.js:182:27)
    at /usr/local/lib/node_modules/opsync/lib/opsync.js:185:13
    at Request._callback (/usr/local/lib/node_modules/opsync/lib/remote.js:52:7)
    at Request.self.callback (/usr/local/lib/node_modules/opsync/node_modules/request/request.js:123:22)
    at Request.emit (events.js:98:17)
    at Request.<anonymous> (/usr/local/lib/node_modules/opsync/node_modules/request/request.js:1047:14)
    at Request.emit (events.js:117:20)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/opsync/node_modules/request/request.js:998:12)
    at IncomingMessage.emit (events.js:117:20)
    at _stream_readable.js:944:16
```
Will these two errors affect the performance/reliability in any way?
The memory leak warning still showing sometimes, but I don't think this is the main problem.

Thank you for your support so far. It has been really helpful! :+1:

**Comment by eliasgs** [comment]
I can't seem to replicate the errors you describe. What version of mongo are you using?

**Comment by rikolumi** [comment]
I'm using 2.6.7 on both ends. I think it has something to do with my config, but not sure which part.

Here is my settings.js:
```
module.exports = {
  mongo: {
    // connection string specifying the location of the oplog
    uri: 'mongodb://127.0.0.1:3001/local',
  },
  stats: {
    // stats can also be enabled by setting environment variable
    // OPSYNC_ENABLE_STATS=true
    enable: true,
    uri: 'mongodb://127.0.0.1:3001/local',
    collection: 'opsync.statsd'
  }
};
```

**Comment by eliasgs** [comment]
Hm, that looks perfectly fine. What version of node are you running? Also can you send me a dump of the  `local.opsync.ignore`, `local.opsync.errors` and `local.opsync.replay` collections?

**Comment by rikolumi** [comment]
Hi, I'm currently using node v0.10.36.

For the database dump I will send it to your email directly. The dump is from recipient database(where server 1 try to send data).

I performed database insertion and update operation in the dump.
